### PR TITLE
OmgSide插件 - XingChenTools & 五连升星抽奖机 & 服务器问答系统

### PR DESCRIPTION
**Pull request by xingchentye**

### CODE REVIEW

**Comment by Torrekie** [comment]
what was that dictionary binary file do? It would be better to make those things customizable or configurable

**Review by RainyHallways — COMMENTED** [review]
It seems okay?(

**Comment by SuperScript-PRC** [comment]
what happened？似乎得让torrekie催下240啥的...

**Comment by Torrekie** [comment]
this PR cannot be merged before we clarify what was that "dictionary" binary

**Comment by CMA2401PT** [comment]
赞同拖拖的说法，以目前的状态是难以被合并的。这不是说你写的东西不好，而是说目前的形式不适合出现在这个位置，如果你感到难以理解的话，可以这么思考：
你的电脑系统会出厂附赠一些游戏，但附带的是国际象棋，空当接龙，三维弹球之类的小玩意，而不会是无人深空，光环之类的游戏。这不是说这两个游戏不好，也不是说运行不起来，只是简单的：不适合附带在系统里而已，你这个就属于类似的情况。
鉴于目前的实际情况，建议可以采取以下行动：
方案1: 利用python语言高动态性的优点，大幅度压缩此组件的程序文件和其它有关文件数量
方案2: 部分文件可以设计为首次运行时下载
方案3: 自行为此组建建立一个仓库

**Comment by Torrekie** [comment]
Glad to see all binaries has been removed, but I still see some problems under current code:
- `tmp` and `log` in *nix systems should follow the base structure, which means paths like `/var/log/fastbuilder/omega_side/packname/*.log` or `/var/tmp/fastbuilder/omega_side/packname/*` should be used instead, this is depending on system, for *nix, you can try `mkstemp`.
- NEVER download external libraries in your script on a system which managed by a package manager (e.g. APT/dpkg), you should warn users that some libraries is missing instead of downloading them without users' agree. I can confirm that "NumPy" and "toml" already has been managed by most vendors and all users should install these dependencies from their package managers.

**Comment by CMA2401PT** [comment]
feel free to reopen

**Pull request closed without merging**
