### PR TITLE
Attempt to fix #153: Ignoring invalid characters on BDump exporting

### LINKED ISSUE #153: 使用 `export` 导出 `命令方块` 时出现的罕见错误
经过分析，得出是下面这种 `buffer` 造成的问题。
```
b'\x01\x00\x00\x00\x00\x01\x00\x01\x00\x1escoreboard players reset * uid"\x84\x01\x00.commands.scoreboard.players.resetscore.success\x04\x03uid.%commands.scoreboard.players.offlinePlayerName\x01\xd2\xdf\xba\x12\x00\x00'
```
```
[1, 0, 0, 0, 0, 1, 0, 1, 0, 30, 115, 99, 111, 114, 101, 98, 111, 97, 114, 100, 32, 112, 108, 97, 121, 101, 114, 115, 32, 114, 101, 115, 101, 116, 32, 42, 32, 117, 105, 100, 34, 132, 1, 0, 46, 99, 111, 109, 109, 97, 110, 100, 115, 46, 115, 99, 111, 114, 101, 98, 111, 97, 114, 100, 46, 112, 108, 97, 121, 101, 114, 115, 46, 114, 101, 115, 101, 116, 115, 99, 111, 114, 101, 46, 115, 117, 99, 99, 101, 115, 115, 4, 3, 117, 105, 100, 46, 37, 99, 111, 109, 109, 97, 110, 100, 115, 46, 115, 99, 111, 114, 101, 98, 111, 97, 114, 100, 46, 112, 108, 97, 121, 101, 114, 115, 46, 111, 102, 102, 108, 105, 110, 101, 80, 108, 97, 121, 101, 114, 78, 97, 109, 101, 1, 210, 223, 186, 18, 0, 0]
```
***
`PhoenixBuilder` 在处理到这种 `buffer` 对应的命令方块时会发生错误。相关的错误提示和 `BDX` 文件中记录的内容如下所示。

D54D41D27CBA243D86A6FD2659A85983

其中，在 `Python` 下，存在 `b'.'[0] = 46` 。

```
b'$\x00\x02\x00\x00\x00\x00scoreboard players reset * uid\x00\x00\x00commands.scoreboard.players.resetscore.success\x00\x00\x00\x00\x00\x01\x00\x00\x01'
```
不难发现，`scoreboard players reset * uid` 后面多了个 `\x00` ，删除后它就正常了。
但是我还是没有找到导致这个 `bug` 的原因，固提交此 `Issue`

### PR DESCRIPTION
**Pull request by Rabbit0w0**

### CODE REVIEW

**Comment by Happy2018new** [comment]
This approach treats the symptoms rather than the root causes.
I think we may need to see how to parse these `NBT` which are incomplete but not use this way to fix bugs.

**Comment by Rabbit0w0** [comment]
> This approach treats the symptoms rather than the root causes. I think we may need to see how to parse these `NBT` which are incomplete but not use this way to fix bugs.

No, it's just formatting data. Also, correcting data before handling is a common solution for this kind of problems. It's **NOT** fixing by symptoms but avoiding unexpected problems in the future.

**Comment by Happy2018new** [comment]
> > This approach treats the symptoms rather than the root causes. I think we may need to see how to parse these `NBT` which are incomplete but not use this way to fix bugs.
> 
> No, it's just formatting data. Also, correcting data before handling is a common solution for this kind of problems. It's **NOT** fixing by symptoms but avoiding unexpected problems in the future.

But you know, this repair method is not entirely reliable.

**Comment by Rabbit0w0** [comment]
> > > This approach treats the symptoms rather than the root causes. I think we may need to see how to parse these `NBT` which are incomplete but not use this way to fix bugs.
> > 
> > 
> > No, it's just formatting data. Also, correcting data before handling is a common solution for this kind of problems. It's **NOT** fixing by symptoms but avoiding unexpected problems in the future.
> 
> But you know, this repair method is not entirely reliable.

All in all, trim the string before handling it is not harmful. And sometimes beneficial, especially in this situation.

**Comment by LNSSPsd** [comment]
`strings.TrimSpace` doesn't really work on removing the trailing `\0`.

**Comment by LNSSPsd** [comment]
Fixed the targeted issue in 8b4040a86199a1ba0cf145deac8e6bc4c2bf5339.

**Comment by Happy2018new** [comment]
必要说明：此 Bug 真正修复于 [13b9438](https://github.com/LNSSPsd/PhoenixBuilder/commit/13b94381d676fe3094502767f5d441419dcb0757)

**Pull request closed without merging**
