### PR TITLE
给拉取请求添加构建检查

### PR DESCRIPTION
**Pull request by RainyHallways**
给拉取请求添加构建检查

### CODE REVIEW

**Comment by Happy2018new** [comment]
看起来还好？

**Comment by Torrekie** [comment]
I have no problem with this, it can be merged anytime

**Comment by RainyHallways** [comment]
Not yet,for sombody who has no access to Github Actions,the Check workflow couldn't work



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月17日 22:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LNSSPsd/PhoenixBuilder] 给拉取请求添加构建检查 (PR #335) |

Not necessary tho, the checking script would run in all the forks, and there's no need to re-run it once again on PRs.

**Comment by LNSSPsd** [comment]
> Not yet,for sombody who has no access to Github Actions,the Check workflow couldn't work
> […](#)

Do you ever think that someone who has no access to Github is able to create a pull request? Github Actions is available for all free accounts.

**Comment by Torrekie** [comment]
Not necessary but better than nothing, sometimes they do PRs before compile check or after creating them

**Comment by LNSSPsd** [comment]
> Not necessary but better than nothing, sometimes they do PRs before compile check or after creating them

No, that won't ever happen, unless they remove the checking workflow

**Comment by RainyHallways** [comment]
As what I say,you can see some fork repos .You'll find that most of these repos are not enable Actions.Why?Because that every repo must agreed Github's EULA then could use Actions.But it is not enabled by default.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月18日 07:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LNSSPsd/PhoenixBuilder] 给拉取请求添加构建检查 (PR #335) |

Not necessary but better than nothing, sometimes they do PRs before compile check or after creating them

No, that won't ever happen, unless they remove the checking workflow

**Comment by LNSSPsd** [comment]
```
By default, GitHub Actions is enabled on all repositories and organizations.
```
- [Managing GitHub Actions settings for a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository)

**Comment by RainyHallways** [comment]
As you see.





---- 回复的原邮件 ----
***@***.***>日期2023年07月18日 ***@***.***>***@***.***>***@***.***>主题Re: [LNSSPsd/PhoenixBuilder] 给拉取请求添加构建检查 (PR #335)
By default, GitHub Actions is enabled on all repositories and organizations.
Managing GitHub Actions settings for a repository

**Comment by RainyHallways** [comment]
https://img1.imgtp.com/2023/07/18/edlWF2kX.jpg

**Comment by LNSSPsd** [comment]
I see

**Pull request merged**
