### PR TITLE
Update the Chinese version of the Bdump file format

### PR DESCRIPTION
**Pull request by Happy2018new**
# Changes
 - Update the Chinese version of the Bdump file format
 - Solve some problems in the original document and added some additions
 - Add the old Chinese version of the document

### CODE REVIEW

**Comment by Happy2018new** [comment]
OK, that's all.

**Comment by Happy2018new** [comment]
应该说明的是，之所以创建 `bdump-cn-old.md` 是希望之后看协议的人可以立刻找到已被移除的特性（如果有一些老旧的 `BDX` 在被研究的话）

**Comment by LNSSPsd** [comment]
The word `protocol` is for network communication, and this is only a `file format`.

**Comment by Happy2018new** [comment]
> The word `protocol` is for network communication, and this is only a `file format`.

ok, @LNSSPsd

**Comment by Happy2018new** [comment]
I think I need create a new pull request.

**Pull request closed without merging**
