### PR TITLE
bdump文档添加繁体中文版文档

### PR DESCRIPTION
**Pull request by HDTianRu**

### CODE REVIEW

**Comment by Torrekie** [comment]
Chinese language is a complexed structure, simply converting characters from Simplified to Traditional is not accepted by our localization policies. Please make sure you DO understand Traditional Chinese before attempting.

**Comment by HDTianRu** [comment]
> Chinese language is a complexed structure, simply converting characters from Simplified to Traditional is not accepted by our localization policies. Please make sure you DO understand Traditional Chinese before attempting.



> Chinese language is a complexed structure, simply converting characters from Simplified to Traditional is not accepted by our localization policies. Please make sure you DO understand Traditional Chinese before attempting.



> Chinese language is a complexed structure, simply converting characters from Simplified to Traditional is not accepted by our localization policies. Please make sure you DO understand Traditional Chinese before attempting.

我今天又问了一下炎欧，让他看了看，他也说没看出啥大问题，估计这个翻译应该没有问题

**Comment by LNSSPsd** [comment]
> > Chinese language is a complexed structure, simply converting characters from Simplified to Traditional is not accepted by our localization policies. Please make sure you DO understand Traditional Chinese before attempting.
> 
> > Chinese language is a complexed structure, simply converting characters from Simplified to Traditional is not accepted by our localization policies. Please make sure you DO understand Traditional Chinese before attempting.
> 
> > Chinese language is a complexed structure, simply converting characters from Simplified to Traditional is not accepted by our localization policies. Please make sure you DO understand Traditional Chinese before attempting.
> 
> 我今天又问了一下炎欧，让他看了看，他也说没看出啥大问题，估计这个翻译应该没有问题

那么如何确认 `zh_TW` 的准确性？

**Comment by Torrekie** [comment]
I wanna point out several wording differences
文件 -> 檔案
命令 -> 指令
运行 -> 執行
设置 -> 設定
When dealing with those *差異用詞*, not only change the words but sentences also. I personally would not recommend to just converting characters.

**Comment by LNSSPsd** [comment]
Closed for direct character conversion

**Pull request closed without merging**
