### PR TITLE
更新兩個繁中的翻譯，並將另外幾種語言的FB改為FastBuilder

### PR DESCRIPTION
**Pull request by YanOu1**

### CODE REVIEW

**Comment by LNSSPsd** [comment]
Localization isn't documentation tho @Happy2018new

**Comment by LNSSPsd** [comment]
Pending until #312 is solved.

**Comment by Happy2018new** [comment]
> Localization isn't documentation tho @Happy2018new

好的，下次我会注意的

**Comment by Torrekie** [comment]
Close as corresponding texts has been removed

**Pull request closed without merging**
