### PR TITLE
some changes for ServerChatroom

### PR DESCRIPTION
**Pull request by SuperScript-PRC**
Correct some details about serverchatroom(SuperLink) and delete useless parts
Change the default ipaddr of central SuperLink-server because the former server was no longer in use.

### CODE REVIEW

**Comment by LNSSPsd** [comment]
What is the server `222.187.232.63:24013`?

**Comment by Liliya233** [comment]
对于Omega，应该使用配置升级的方式来更改默认的IP地址，而不是直接在代码中进行变更

**Comment by SuperScript-PRC** [comment]
> 对于Omega，应该使用配置升级的方式来更改默认的IP地址，而不是直接在代码中进行变更

喔，谢谢，omega这方面我不是很懂，thanks for your advice

**Comment by SuperScript-PRC** [comment]
ah it's a new chatroom server and it's similar with [124.222.13.238] and wr're sure it is **safer** and faster to connect than the former server

> What is the server ?`222.187.232.63:24013`

**Pull request closed without merging**
